version: '3.7'

services:
  postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: testtest
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: coindesk

  scheduler:
    image: btc-coindesk-subscriber:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/coindesk
      - SPRING_DATASOURCE_USERNAME=testtest
      - SPRING_DATASOURCE_PASSWORD=pgpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:main
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

